name: Continuous Integration

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13

    - run: mvn -q test
    - run: mvn -q package
    - run: mvn -q javadoc:javadoc
    - run: touch ./target/site/apidocs/.nojekyll

    - name: Deploy
      if: github.ref == 'refs/heads/master' && success()
      uses: peaceiris/actions-gh-pages@v2.10.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/site/apidocs
      with:
        commitMessage: ${{ github.event.head_commit.message }}
        username: "Github Actions"
        useremail: "actions@github"
